In [1]:
import polars
import pandas

In [21]:
PATH = "../01_crawl_wikipedia/dataset.parquet"

In [23]:
%%timeit
pandas.read_parquet(PATH).groupby("word").agg({"ipa": list})

57.4 ms ± 677 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [24]:
%%timeit
polars.read_parquet(PATH).groupby("word")\
    .agg(polars.col("ipa").list())

3.15 ms ± 60.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [27]:
%%timeit
polars.read_parquet(PATH).lazy()\
    .groupby("word")\
    .agg(polars.col("ipa").list())

614 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [2]:
%timeit df_pl = polars.read_parquet(PATH)
%timeit df_pd = pandas.read_parquet(PATH)

578 µs ± 17.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
4.85 ms ± 17.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]:
df_pl = polars.read_parquet(PATH)
df_pd = pandas.read_parquet(PATH)

df_pl.head()

shape: (5, 4)
┌─────────────────────────┬─────┬──────┬────────────────────┐
│ context                 ┆ ipa ┆ word ┆ context_proc       │
│ ---                     ┆ --- ┆ ---  ┆ ---                │
│ str                     ┆ str ┆ str  ┆ str                │
╞═════════════════════════╪═════╪══════╪════════════════════╡
│ (UK, US)  |             ┆ eɪ  ┆ a    ┆ UK, US             │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ (General Australian)  | ┆ æɪ  ┆ a    ┆ General Australian │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ (phoneme)  |            ┆ æ   ┆ a    ┆ phoneme            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ (phoneme)  |            ┆ ɑː  ┆ a    ┆ phoneme            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ (phoneme)  |            ┆ eɪ  ┆ a    ┆ phoneme            │
└─────────────────────────┴─────┴──────┴────────────────────┘

In [5]:
%timeit df_pl.filter(polars.col("context_proc") == "phoneme")
%timeit df_pd.loc[df_pd.context_proc == "phoneme"]

192 µs ± 3.44 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
493 µs ± 3.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [18]:
%timeit df_pl.groupby("word").agg(polars.col("ipa").list())
%timeit df_pd.groupby("word").agg({"ipa": list})

2.57 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
49.3 ms ± 277 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [20]:
df_pl.groupby("word").agg(polars.col("ipa").list())

shape: (4739, 2)
┌───────────┬─────────────────────────────────────┐
│ word      ┆ ipa                                 │
│ ---       ┆ ---                                 │
│ str       ┆ list[str]                           │
╞═══════════╪═════════════════════════════════════╡
│ delegate  ┆ ["ˈdɛlɪɡət"]                        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ submit    ┆ ["səbˈmɪt"]                         │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ four      ┆ ["fɔː", "fo(ː)ɹ", ... "foː"]        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ get       ┆ ["ɡɛt", "ɡɪt"]                      │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...       ┆ ...                                 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ somewhere ┆ ["ˈsʌm.wɛɹ", "ˈsʌm.ʍɛɹ", ... "ˈs... │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ apparatus ┆ ["æp.əˈɹeɪ.təs", "æp.əˈɹæt.əs", ... │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ magnetic  ┆ ["mæɡˈnɛtɪk"]                       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ strictly  ┆ ["ˈstɹɪktli"]                       │
└───────────┴─────────────────────────────────────┘